# Generated by Django 3.2.16 on 2023-01-18 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='vote',
        ),
        migrations.AddField(
            model_name='reply',
            name='vote_users',
            field=models.ManyToManyField(related_name='vote_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
