# Generated by Django 3.2.16 on 2023-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('nums', models.CharField(max_length=50)),
                ('pick_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
