# Generated by Django 3.2.16 on 2023-01-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=4),
        ),
    ]
